/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salmans;

import java.util.ArrayList;
import javax.swing.JDialog;

/**
 *
 * @author rick
 */
public class SalmansGUI extends javax.swing.JFrame {

    /**
     * Creates new form SalmansGUI
     */
    public SalmansGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_almacen = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jt_ingrediente = new javax.swing.JTextField();
        btn_addIngredient = new javax.swing.JButton();
        jd_productos = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm_almacen = new javax.swing.JMenuItem();
        jm_productos = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jLabel1.setText("Almacén");

        btn_addIngredient.setText("Agregar Ingrediente al almacén");
        btn_addIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addIngredientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_almacenLayout = new javax.swing.GroupLayout(jd_almacen.getContentPane());
        jd_almacen.getContentPane().setLayout(jd_almacenLayout);
        jd_almacenLayout.setHorizontalGroup(
            jd_almacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_almacenLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jt_ingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(jd_almacenLayout.createSequentialGroup()
                .addGroup(jd_almacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_addIngredient)
                    .addGroup(jd_almacenLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_almacenLayout.setVerticalGroup(
            jd_almacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_almacenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jt_ingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_addIngredient)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_productosLayout = new javax.swing.GroupLayout(jd_productos.getContentPane());
        jd_productos.getContentPane().setLayout(jd_productosLayout);
        jd_productosLayout.setHorizontalGroup(
            jd_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_productosLayout.setVerticalGroup(
            jd_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Opciones");

        jm_almacen.setText("Almacen");
        jm_almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_almacenActionPerformed(evt);
            }
        });
        jMenu1.add(jm_almacen);

        jm_productos.setText("Productos");
        jm_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_productosActionPerformed(evt);
            }
        });
        jMenu1.add(jm_productos);

        jMenuItem3.setText("jMenuItem3");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_almacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_almacenActionPerformed
        openDialog(this.jd_almacen);
    }//GEN-LAST:event_jm_almacenActionPerformed

    private void jm_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_productosActionPerformed
        openDialog(this.jd_productos);
    }//GEN-LAST:event_jm_productosActionPerformed

    private void btn_addIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addIngredientActionPerformed
        String newIngredient = jt_ingrediente.getText();
        boolean newItem = true;

        for (int i = 0; i < almacen.size(); i++) {
            for (int j = 0; j < almacen.get(i).size(); j++) {
                if (newIngredient.equalsIgnoreCase(almacen.get(i).get(j))){
                    almacen.get(i).add(newIngredient.toLowerCase());
                    newItem=false;
                    break;
                }else{
                    newItem = true;
                }
            }
        }
        if (newItem){
            almacen.add(new ArrayList());
            almacen.get(almacen.size()-1).add(newIngredient.toLowerCase());
        }
        
    }//GEN-LAST:event_btn_addIngredientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalmansGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalmansGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalmansGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalmansGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalmansGUI().setVisible(true);
            }
        });
    }
    
    public void openDialog(JDialog dialog){
        dialog.setLocationRelativeTo(this);
        dialog.setModal(true);
        dialog.pack();
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addIngredient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JDialog jd_almacen;
    private javax.swing.JDialog jd_productos;
    private javax.swing.JMenuItem jm_almacen;
    private javax.swing.JMenuItem jm_productos;
    private javax.swing.JTextField jt_ingrediente;
    // End of variables declaration//GEN-END:variables
    private ArrayList<ArrayList<String>> almacen  = new ArrayList();
    private ArrayList<Producto> productos = new ArrayList();


}
