/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salmans;

import java.util.ArrayList;
import java.util.Queue;
import java.util.Stack;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author rick
 */
public class SalmansGUI extends javax.swing.JFrame {

    /**
     * Creates new form SalmansGUI
     */
    public SalmansGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.camiones.add(new ArrayList());
        this.camiones.add(new ArrayList());
        this.camiones.add(new ArrayList());
        this.camiones.add(new ArrayList());
        this.camiones.add(new ArrayList());
        this.camiones.add(new ArrayList());
        cocinero1 = new Cocinero(this.progressBar1,this.camiones);
        cocinero2 = new Cocinero(this.progressBar2,this.camiones);
        cocinero3 = new Cocinero(this.progressBar3,this.camiones);
        cocinero4 = new Cocinero(this.progressBar4,this.camiones);
        cocinero5 = new Cocinero(this.progressBar5,this.camiones);
        cocinero6 = new Cocinero(this.progressBar6,this.camiones);
        cocinero1.start();
        cocinero2.start();
        cocinero3.start();
        cocinero4.start();
        cocinero5.start();
        cocinero6.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_almacen = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jt_ingrediente = new javax.swing.JTextField();
        btn_addIngredient = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_almacen = new javax.swing.JList();
        jd_productos = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_ingredientes = new javax.swing.JList();
        jt_tiempo = new javax.swing.JTextField();
        jt_precio = new javax.swing.JTextField();
        jt_nombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jt_tiempo1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_ingredientes1 = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        btn_eliminarIngrediente = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jt_nombre1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jt_precio1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jc_productos = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_eliminarIngredientes = new javax.swing.JList();
        jButton6 = new javax.swing.JButton();
        jd_ordenes = new javax.swing.JDialog();
        jt_numOrden = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_menu = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_ordenes = new javax.swing.JList();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jd_cocina = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        progressBar2 = new javax.swing.JProgressBar();
        progressBar3 = new javax.swing.JProgressBar();
        progressBar1 = new javax.swing.JProgressBar();
        progressBar5 = new javax.swing.JProgressBar();
        progressBar6 = new javax.swing.JProgressBar();
        progressBar4 = new javax.swing.JProgressBar();
        jd_camiones = new javax.swing.JDialog();
        jc_camiones = new javax.swing.JComboBox();
        jButton10 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_camiones = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm_almacen = new javax.swing.JMenuItem();
        jm_productos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jd_almacen.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_almacenWindowClosing(evt);
            }
        });

        jLabel1.setText("Almacén");

        btn_addIngredient.setText("Agregar Ingrediente al almacén");
        btn_addIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addIngredientActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(jl_almacen);

        javax.swing.GroupLayout jd_almacenLayout = new javax.swing.GroupLayout(jd_almacen.getContentPane());
        jd_almacen.getContentPane().setLayout(jd_almacenLayout);
        jd_almacenLayout.setHorizontalGroup(
            jd_almacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_almacenLayout.createSequentialGroup()
                .addGroup(jd_almacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_almacenLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jt_ingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_almacenLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btn_addIngredient))
                    .addGroup(jd_almacenLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1)))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_almacenLayout.setVerticalGroup(
            jd_almacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_almacenLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jt_ingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_addIngredient)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(jd_almacenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );

        jd_productos.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_productosWindowClosing(evt);
            }
        });

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel2.setText("Tiempo de Preparacion (segundos)");

        jLabel3.setText("Nombre");

        jLabel4.setText("Precio");

        jLabel5.setText("Lista de Ingredientes");

        jScrollPane1.setViewportView(jl_ingredientes);

        jButton1.setText("Agregar Ingrediente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar Producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        jLabel7.setText("Tiempo de Preparacion (segundos)");

        jScrollPane2.setViewportView(jl_ingredientes1);

        jLabel9.setText("Lista de Ingredientes");

        btn_eliminarIngrediente.setText("Eliminar Ingrediente");
        btn_eliminarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarIngredienteActionPerformed(evt);
            }
        });

        jButton4.setText("Agregar Ingrediente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre");

        jLabel8.setText("Precio");

        jButton3.setText("Modificar Producto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Cargar Producto");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jt_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addComponent(btn_eliminarIngrediente)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jt_tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jc_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_eliminarIngrediente)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jc_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jt_tiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jt_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificar", jPanel2);

        jScrollPane3.setViewportView(jl_eliminarIngredientes);

        jButton6.setText("Eliminar Producto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(331, 331, 331))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton6)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel3);

        javax.swing.GroupLayout jd_productosLayout = new javax.swing.GroupLayout(jd_productos.getContentPane());
        jd_productos.getContentPane().setLayout(jd_productosLayout);
        jd_productosLayout.setHorizontalGroup(
            jd_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jd_productosLayout.setVerticalGroup(
            jd_productosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_productosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jd_ordenes.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_ordenesWindowClosing(evt);
            }
        });

        jLabel10.setText("Número de Orden");

        jScrollPane4.setViewportView(jl_menu);

        jScrollPane5.setViewportView(jl_ordenes);

        jButton7.setText("Agregar a la Orden");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Eliminar de la Orden");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("<-----");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setText("----->");

        jButton9.setText("Completar Orden");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ordenesLayout = new javax.swing.GroupLayout(jd_ordenes.getContentPane());
        jd_ordenes.getContentPane().setLayout(jd_ordenesLayout);
        jd_ordenesLayout.setHorizontalGroup(
            jd_ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ordenesLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(160, 160, 160))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ordenesLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(211, 211, 211))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ordenesLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jd_ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ordenesLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ordenesLayout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(347, 347, 347))))
            .addGroup(jd_ordenesLayout.createSequentialGroup()
                .addGroup(jd_ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ordenesLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jt_numOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_ordenesLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_ordenesLayout.setVerticalGroup(
            jd_ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ordenesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jt_numOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jd_ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ordenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jd_cocina.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_cocinaWindowClosing(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel13.setText("Cocina");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setText("Cocinero 1");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setText("Cocinero 2");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel16.setText("Cocinero 3");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setText("Cocinero 5");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setText("Cocinero 4");

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setText("Cocinero 6");

        javax.swing.GroupLayout jd_cocinaLayout = new javax.swing.GroupLayout(jd_cocina.getContentPane());
        jd_cocina.getContentPane().setLayout(jd_cocinaLayout);
        jd_cocinaLayout.setHorizontalGroup(
            jd_cocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_cocinaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jd_cocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jd_cocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(progressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        jd_cocinaLayout.setVerticalGroup(
            jd_cocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_cocinaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addGap(47, 47, 47)
                .addGroup(jd_cocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(progressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jd_cocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_cocinaLayout.createSequentialGroup()
                        .addGroup(jd_cocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(progressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel16))
                    .addComponent(progressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jd_cocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(progressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jd_cocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_cocinaLayout.createSequentialGroup()
                        .addGroup(jd_cocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(progressBar5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel19))
                    .addComponent(progressBar6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        jd_camiones.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_camionesWindowClosing(evt);
            }
        });

        jButton10.setText("Cargar Lista de Ordenes ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(jl_camiones);

        javax.swing.GroupLayout jd_camionesLayout = new javax.swing.GroupLayout(jd_camiones.getContentPane());
        jd_camiones.getContentPane().setLayout(jd_camionesLayout);
        jd_camionesLayout.setHorizontalGroup(
            jd_camionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_camionesLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jd_camionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addComponent(jc_camiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jd_camionesLayout.setVerticalGroup(
            jd_camionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_camionesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jd_camionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_camionesLayout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jc_camiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");

        jm_almacen.setText("Almacen");
        jm_almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_almacenActionPerformed(evt);
            }
        });
        jMenu1.add(jm_almacen);

        jm_productos.setText("Productos");
        jm_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_productosActionPerformed(evt);
            }
        });
        jMenu1.add(jm_productos);

        jMenuItem1.setText("Ordenar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cocina");

        jMenuItem2.setText("Chefs");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transporte");

        jMenuItem3.setText("Camiones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ventas");

        jMenuItem5.setText("Total Ganancias");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_almacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_almacenActionPerformed
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < almacen.size(); i++) {
            for (int j = 0; j < almacen.get(i).size(); j++) {
                model.addElement(almacen.get(i).peek());
            }
        }
        this.jl_almacen.setModel(model);
        openDialog(this.jd_almacen);
    }//GEN-LAST:event_jm_almacenActionPerformed

    private void jm_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_productosActionPerformed
        openDialog(this.jd_productos);
        this.ingredientesTemp = new ArrayList();
    }//GEN-LAST:event_jm_productosActionPerformed

    private void btn_addIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addIngredientActionPerformed
        String newIngredient = jt_ingrediente.getText();
        boolean newItem = true;

        for (int i = 0; i < almacen.size(); i++) {
            for (int j = 0; j < almacen.get(i).size(); j++) {
                if (newIngredient.equalsIgnoreCase((String)almacen.get(i).peek())){
                    almacen.get(i).add(newIngredient.toLowerCase());
                    newItem=false;
                    break;
                }
            }
        }
        if (newItem){
            almacen.add(new Stack());
            almacen.get(almacen.size()-1).add(newIngredient.toLowerCase());
        }
        
        this.jt_ingrediente.setText("");
        JOptionPane.showMessageDialog(this, "Ingrediente Agregado al Almacén", "", JOptionPane.INFORMATION_MESSAGE);
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < almacen.size(); i++) {
            for (int j = 0; j < almacen.get(i).size(); j++) {
                model.addElement(almacen.get(i).peek());
            }
        }
        this.jl_almacen.setModel(model);
    }//GEN-LAST:event_btn_addIngredientActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String temp = JOptionPane.showInputDialog(this, "Porfavor ingrese el nuevo Ingrediente");
        ingredientesTemp.add(temp);
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < ingredientesTemp.size(); i++) {
            model.addElement(ingredientesTemp.get(i));
        }
        this.jl_ingredientes.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.ingredientesTemp.isEmpty()){
            JOptionPane.showMessageDialog(this, "La lista de ingredientes esta vacia", "Error", WIDTH);
        }else{
            String nombre = this.jt_nombre.getText();
            int tiempo = Integer.parseInt(this.jt_tiempo.getText());
            int precio = Integer.parseInt(this.jt_precio.getText());
            productos.add(new Producto(this.ingredientesTemp,tiempo,nombre,precio));
            JOptionPane.showMessageDialog(this, "Producto Agregado");
            this.jt_nombre.setText("");
            this.jt_precio.setText("");
            this.jt_tiempo.setText("");
            this.jl_ingredientes.setModel(new DefaultListModel());
            this.ingredientesTemp = new ArrayList();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nombre = this.jt_nombre1.getText();
        int precio = Integer.parseInt(this.jt_precio1.getText());
        int tiempo = Integer.parseInt(this.jt_tiempo1.getText());
        productos.get(indexGlobal).setNombre(nombre);
        productos.get(indexGlobal).setPrecio(precio);
        productos.get(indexGlobal).setTiempo(tiempo);
        this.jt_nombre1.setText("");
        this.jt_precio1.setText("");
        this.jt_tiempo1.setText("");
        this.jl_ingredientes1.setModel(new DefaultListModel());
        JOptionPane.showMessageDialog(null, "Producto modificado con exito");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String temp = JOptionPane.showInputDialog(this, "Porfavor ingrese el nuevo Ingrediente");
        productos.get(indexGlobal).getIngredientes().add(temp);
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < productos.get(indexGlobal).getIngredientes().size(); i++) {
            model.addElement(productos.get(indexGlobal).getIngredientes().get(i));
        }
        this.jl_ingredientes1.setModel(model);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        DefaultComboBoxModel model1 = new DefaultComboBoxModel();
        
        for (int i = 0; i < this.productos.size(); i++) {
            model.addElement(productos.get(i).getNombre());
            model1.addElement(productos.get(i).toString());
        }
        this.jl_eliminarIngredientes.setModel(model1);
        this.jc_productos.setModel(model);
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        indexGlobal = this.jc_productos.getSelectedIndex();
        if (indexGlobal != -1){
            this.jt_nombre1.setText(productos.get(indexGlobal).getNombre());
            this.jt_precio1.setText(Integer.toString(productos.get(indexGlobal).getPrecio()));
            this.jt_tiempo1.setText(Integer.toString(productos.get(indexGlobal).getTiempo()));
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < productos.get(indexGlobal).getIngredientes().size(); i++) {
                model.addElement(productos.get(indexGlobal).getIngredientes().get(i));
            }
            this.jl_ingredientes1.setModel(model);
            this.ingredientesTemp = productos.get(indexGlobal).getIngredientes();
        }else{
            JOptionPane.showMessageDialog(this, "No se ha seleccionado nada del comboBox", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_eliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarIngredienteActionPerformed
        int index = this.jl_ingredientes1.getSelectedIndex();
        if (index != -1){
            productos.get(indexGlobal).getIngredientes().remove(index);
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < productos.get(indexGlobal).getIngredientes().size(); i++) {
                model.addElement(productos.get(indexGlobal).getIngredientes().get(i));
            }
            this.jl_ingredientes1.setModel(model);
        }else{
            JOptionPane.showMessageDialog(this, "No se ha seleccionado nada de la lista", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_eliminarIngredienteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int index = this.jl_eliminarIngredientes.getSelectedIndex();
        if (index != -1){
            productos.remove(index);
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < productos.size(); i++) {
                model.addElement(productos.get(i));
            }
            this.jl_eliminarIngredientes.setModel(model);
        }else{
            JOptionPane.showMessageDialog(this, "No hay ningun elemento de la lista seleccionado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < productos.size(); i++) {
            model.addElement(productos.get(i));
        }
        this.jl_menu.setModel(model);
        openDialog(this.jd_ordenes);
        ordenTemp = new Orden();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int index = jl_menu.getSelectedIndex();
        if(index != -1){
            ordenTemp.getListaProductos().add(productos.get(index));
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < ordenTemp.getListaProductos().size(); i++) {
                model.addElement(ordenTemp.getListaProductos().get(i).toString());
            }
            this.jl_ordenes.setModel(model);
        }else{
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningun elemento de la lista", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int index = this.jl_ordenes.getSelectedIndex();
        if(index != -1){
            ordenTemp.getListaProductos().remove(index);
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < ordenTemp.getListaProductos().size(); i++) {
                model.addElement(ordenTemp.getListaProductos().get(index).toString());
            }
            this.jl_ordenes.setModel(model);
        }else{
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningun elemento de la lista", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String temp = this.jt_numOrden.getText();
        int tiempo=0;
        boolean isTaken = false;
        for (int i = 0; i < this.ordenesTomadas.size(); i++) {
            if (temp.equalsIgnoreCase(ordenesTomadas.get(i))){
                isTaken = true;
                break;
            }
        }
        if (ordenTemp.getListaProductos().isEmpty()){
            JOptionPane.showMessageDialog(this, "Esta orden no tiene productos", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if (temp.isEmpty() || isTaken){
                JOptionPane.showMessageDialog(this, "El numero de orden No es valido o ya se ha tomado ese numero", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                boolean proceed = true;
                ArrayList<Boolean> tieneIngredientes = new ArrayList();
                ArrayList<String> ingredientesTemp = new ArrayList();
                for (int i = 0; i < ordenTemp.getListaProductos().size(); i++) {
                    for (int j = 0; j < ordenTemp.getListaProductos().get(i).getIngredientes().size(); j++) {
                        ingredientesTemp.add(ordenTemp.getListaProductos().get(i).getIngredientes().get(j));
                    }
                }
                for (int i = 0; i < ingredientesTemp.size(); i++) {
                    tieneIngredientes.add(false);
                }
                for (int i = 0; i < ingredientesTemp.size(); i++) {
                    for (int j = 0; j < almacen.size(); j++) {
                        try {
                            if (!almacen.get(j).empty()){
                                if(ingredientesTemp.get(i).equalsIgnoreCase((String)almacen.get(j).peek())){   
                                    almacen.get(j).pop();
                                    tieneIngredientes.set(i, true);
                                    break;
                                }   
                            }
                        } catch (Exception e) {
                            
                        }
                            
                    }
                }
                for (int i = 0; i < tieneIngredientes.size(); i++) {
                    if(tieneIngredientes.get(i) == false){
                        proceed = false;
                        break;
                    }
                }
                
                if (proceed){
                    for (int i = 0; i < ordenTemp.getListaProductos().size(); i++) {
                        tiempo+= ordenTemp.getListaProductos().get(i).getTiempo();
                    }
                    ordenTemp.setNumeroOrden(temp);
                    this.ordenesTomadas.add(temp);
                    this.ordenes.add(ordenTemp);
                    JOptionPane.showMessageDialog(this, "Su orden ha sido tomada, tiempo de preparación: "+tiempo);
                    this.jt_numOrden.setText("");
                    this.jl_menu.setModel(new DefaultListModel());
                    this.jl_ordenes.setModel(new DefaultListModel());
                    this.gananciasDelDia+=ordenTemp.getPrecioTotal();
                    int MinOrders = Integer.MAX_VALUE;
                    int index=-1;
                    ArrayList<Cocinero> temp2 = new ArrayList();
                    temp2.add(cocinero1);
                    temp2.add(cocinero2);
                    temp2.add(cocinero3);
                    temp2.add(cocinero4);
                    temp2.add(cocinero5);
                    temp2.add(cocinero6);
                    for (int i = 0; i < temp2.size(); i++) {
                        if (MinOrders> temp2.get(i).getOrdenes().size()){
                            MinOrders = temp2.get(i).getOrdenes().size();
                            index = i;
                        }
                    }

                    System.out.println(index);
                    if (index ==0){
                        cocinero1.getOrdenes().add(ordenTemp);

                    }else if(index==1){
                        cocinero2.getOrdenes().add(ordenTemp);

                    }else if(index==2){
                        cocinero3.getOrdenes().add(ordenTemp);

                    }else if(index==3){
                        cocinero4.getOrdenes().add(ordenTemp);

                    }else if(index==4){
                        cocinero5.getOrdenes().add(ordenTemp);

                    }else if(index==5){
                        cocinero6.getOrdenes().add(ordenTemp);

                    }
                    ordenTemp = new Orden();
                    DefaultListModel model = new DefaultListModel();
                    for (int i = 0; i < productos.size(); i++) {
                        model.addElement(productos.get(i).toString());
                    }
                    jl_menu.setModel(model);
                }else{
                    JOptionPane.showMessageDialog(this, "No hay ingredientes en el almacen", "Error", JOptionPane.ERROR_MESSAGE);
                    this.jl_ordenes.setModel(new DefaultListModel());
                    ordenTemp = new Orden();
        
                }
            }
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jd_ordenesWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_ordenesWindowClosing
        this.setVisible(true);
        this.jt_numOrden.setText("");
        this.jl_menu.setModel(new DefaultListModel());
        this.jl_ordenes.setModel(new DefaultListModel());
    }//GEN-LAST:event_jd_ordenesWindowClosing

    private void jd_almacenWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_almacenWindowClosing
        this.setVisible(true);
    }//GEN-LAST:event_jd_almacenWindowClosing

    private void jd_productosWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_productosWindowClosing
        this.setVisible(true);
        this.jl_ingredientes.setModel(new DefaultListModel());
        this.jl_ingredientes1.setModel(new DefaultListModel());
        this.jt_nombre.setText("");
        this.jt_precio.setText("");
        this.jt_tiempo.setText("");
        this.jt_nombre1.setText("");
        this.jt_precio1.setText("");
        this.jt_tiempo1.setText("");
    }//GEN-LAST:event_jd_productosWindowClosing

    private void jd_cocinaWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_cocinaWindowClosing
        this.setVisible(true);
    }//GEN-LAST:event_jd_cocinaWindowClosing

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        openDialog(this.jd_cocina);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < 6; i++) {
            model.addElement("camion "+(i+1));
        }
        this.jc_camiones.setModel(model);
        openDialog(this.jd_camiones);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JOptionPane.showMessageDialog(this, "Las ganancias fueron de "+this.gananciasDelDia+ " Lempiras");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int index = this.jc_camiones.getSelectedIndex();
        if (index !=-1){
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < this.camiones.get(index).size(); i++) {
                model.addElement("Numero de Orden: "+this.camiones.get(index).get(i).getNumeroOrden());
            }
            this.jl_camiones.setModel(model);
        }else{
            JOptionPane.showMessageDialog(this, "Error, no ha seleccionado un índice válido.");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jd_camionesWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_camionesWindowClosing
        this.setVisible(true);
    }//GEN-LAST:event_jd_camionesWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalmansGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalmansGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalmansGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalmansGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalmansGUI().setVisible(true);
            }
        });
    }
    
    public void openDialog(JDialog dialog){
        this.setVisible(false);
        dialog.setLocationRelativeTo(this);
        dialog.setModal(true);
        dialog.pack();
        dialog.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addIngredient;
    private javax.swing.JButton btn_eliminarIngrediente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox jc_camiones;
    private javax.swing.JComboBox jc_productos;
    private javax.swing.JDialog jd_almacen;
    private javax.swing.JDialog jd_camiones;
    private javax.swing.JDialog jd_cocina;
    private javax.swing.JDialog jd_ordenes;
    private javax.swing.JDialog jd_productos;
    private javax.swing.JList jl_almacen;
    private javax.swing.JList jl_camiones;
    private javax.swing.JList jl_eliminarIngredientes;
    private javax.swing.JList jl_ingredientes;
    private javax.swing.JList jl_ingredientes1;
    private javax.swing.JList jl_menu;
    private javax.swing.JList jl_ordenes;
    private javax.swing.JMenuItem jm_almacen;
    private javax.swing.JMenuItem jm_productos;
    private javax.swing.JTextField jt_ingrediente;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_nombre1;
    private javax.swing.JTextField jt_numOrden;
    private javax.swing.JTextField jt_precio;
    private javax.swing.JTextField jt_precio1;
    private javax.swing.JTextField jt_tiempo;
    private javax.swing.JTextField jt_tiempo1;
    private javax.swing.JProgressBar progressBar1;
    private javax.swing.JProgressBar progressBar2;
    private javax.swing.JProgressBar progressBar3;
    private javax.swing.JProgressBar progressBar4;
    private javax.swing.JProgressBar progressBar5;
    private javax.swing.JProgressBar progressBar6;
    // End of variables declaration//GEN-END:variables
    int indexGlobal;
    private ArrayList<Stack> almacen  = new ArrayList();
    private ArrayList<Producto> productos = new ArrayList();
    private ArrayList<String> ingredientesTemp = new ArrayList();
    private ArrayList<Orden> ordenes = new ArrayList();
    private Orden ordenTemp = new Orden();
    double gananciasDelDia=0;
    private ArrayList<String> ordenesTomadas = new ArrayList();
    private ArrayList<ArrayList<Orden>> camiones = new ArrayList();
    Cocinero cocinero1;
    Cocinero cocinero2;
    Cocinero cocinero3;
    Cocinero cocinero4;
    Cocinero cocinero5;
    Cocinero cocinero6;
    boolean startedThread = false;
    Hilo hil;
    
}
